<?php
/**
 * @file
 * Code for the UIB Message feature.
 */

include_once 'uib_message.features.inc';

/**
 * Implements hook_menu().
 */
function uib_message_menu() {
  $items["api/msg"] = array(
    'page callback' => 'uib_message__msg',
    'access callback' => TRUE,
  );
  $items["it/driftsmeldinger/siste.html"] = array(
    'page callback' => 'uib_message__it_ops_recent',
    'file' => 'uib_message.it_ops.inc',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Return message objects as JSON based on parameters
 *
 * Input parameters could be
 * 1: NodeID
 * 2: Area
 * 3: Username
 * 4: Language
 * 5: Markup
 * 6: Limit
 * 7: Offset
 */
function uib_message__msg() {
  $msgid = null;
  $area = 0;
  $tag = 0;
  $username = "";
  $language = "nb";
  $markup = "JSON";
  $offset = 0;
  $limit = 10;
  $qp = drupal_get_query_parameters();

  $node = null;

  if (!empty($qp)) {
    if (isset($qp['msgid']) && $qp['msgid']) {
      $msgid = $qp['msgid'];
    }
    if (isset($qp['area']) && $qp['area']) {
      $area = $qp['area'];
    }
    if (isset($qp['user']) && $qp['user']) {
      $username = $qp['user'];
    }
    if (isset($qp['language']) && $qp['language']) {
      $language = $qp['language'];
    }
    if (isset($qp['markup']) && $qp['markup']) {
      $markup = $qp['markup'];
    }
    if (isset($qp['limit']) && $qp['limit']) {
      $limit = $qp['limit'];
    }
    if (isset($qp['offset']) && $qp['offset']) {
      $offset = $qp['offset'];
    }
    if (isset($qp['tag']) && $qp['tag']) {
      $tag = $qp['tag'];
    }
  }

  $data = array();
  if (isset($msgid)) {
    $data['msg'][] = uib_message__msg_node_to_array($msgid, $language);
  }
  else if ($area) {
    if (!is_numeric($area)) {
      $area = db_query('SELECT nid FROM node WHERE type LIKE :type AND LOWER(title) LIKE :title',
        array(':type'=>'area',':title' => strtolower($area)))->fetchField();
    }
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type','node');
    $query->entityCondition('bundle','uib_message');
    $query->fieldCondition('field_uib_message_area','target_id',$area);
    if ($language == 'en') {
      $query->fieldCondition('field_uib_message_text_en','value','NULL','!=');
    }
    $query->propertyOrderBy('created', 'DESC');
    $query->range($offset, $limit);
    $result = $query->execute();
    $nids = array_keys($result['node']);
    $nodes = node_load_multiple($nids);
    foreach ($nodes as $nid => $node) {
      $row = uib_message__msg_node_to_array($node->nid, $language);
      if ($row) {
        $data['msg'][] = $row;
      }
    }
  }

  if (!empty($username)) {
    $user = user_load_by_name($username);
    if (!$user) {
      $data['error'] = 'No such user';
    }
    else {
      // Some known node IDs
      $AREA_IT = '77318';
      $AREA_EIA = '77319';
      $AREA_EMPLOYEE_PAGES = '1';

      $area = db_query(
        "SELECT entity_id FROM {field_data_field_uib_staff} WHERE field_uib_staff_target_id = :uid",
        array(':uid' => $user->uid)
      );
      $areas = array(
        $AREA_EMPLOYEE_PAGES,
      );
      foreach ($area as $k) {
        uib_area__get_parentage($k->entity_id, $areas);
      }
      $areas = array_unique($areas);
      $result = db_query(
        "SELECT node.nid, area.field_uib_message_area_target_id AS aid
           FROM {node}, {field_data_field_uib_message_area} AS area, {taxonomy_term_data} AS tax, {field_data_field_uib_message_tag} AS tag
          WHERE (tax.tid = tag.field_uib_message_tag_target_id AND tag.entity_id=node.nid) AND node.type='uib_message' AND node.nid=area.entity_id AND ((area.field_uib_message_area_target_id IN (:area_it,:area_eia) AND tax.name='Drift/Operations') OR area.field_uib_message_area_target_id IN (:areas))
       ORDER BY node.created DESC
          LIMIT :limit OFFSET :offset",
        array(
          ':areas' => $areas,
          ':area_it' => $AREA_IT,
          ':area_eia' => $AREA_EIA,
          ':limit' => $limit,
          ':offset' => $offset,
        )
      );
      foreach ($result as $node) {
        $row = uib_message__msg_node_to_array($node->nid, $language);
        if ($row) {
          $data['msg'][] = $row;
        }
      }
    }
  }
  drupal_add_http_header('Access-Control-Allow-Origin', '*');
  return drupal_json_output($data);
}

function uib_message__msg_node_to_array($nid, $language) {
  $node = node_load($nid);
  if (!$node)
    return;
  $row = array('id' => (int)$node->nid);
  if ($language == 'en' && empty($node->field_uib_message_text_en['und'][0]['value'])) return;
  if ($language == 'nb' && empty($node->field_uib_message_text_nb['und'][0]['value'])) $language = 'en';

  if ($language == 'nb') {
    $row['text'] = $node->field_uib_message_text_nb['und'][0]['value'];
    if (!empty($node->field_uib_message_link_nb))
      $row['link'] = $node->field_uib_message_link_nb['und'][0]['url'];
  }
  if ($language == 'en') {
    $row['text'] = $node->field_uib_message_text_en['und'][0]['value'];
    if (!empty($node->field_uib_message_link_en))
      $row['link'] = $node->field_uib_message_link_en['und'][0]['url'];
  }

  $term = taxonomy_term_load($node->field_uib_message_tag['und'][0]['target_id']);
  $tag = explode('/', $term->name);
  $row['tag'] = $language == 'nb' ? $tag[0] : $tag[1];

  $area_node = node_load($node->field_uib_message_area['und'][0]['target_id']);
  if ($area_node->language != $language) {
    // find area node in the right language
    $result = db_select('node', 'n')
      ->fields('n', array('nid'))
      ->condition('tnid', $area_node->tnid)
      ->condition('language', $language)
      ->execute();
    $nid = $result->fetchField();
    if ($nid) {
      $area_node = node_load($nid);
    }
  }
  $row['area'] = $area_node->title;
  $languages = language_list();
  $row['area_link'] = url("node/$area_node->nid", array('absolute' => true, 'language' => $languages[$language]));

  $row['posted'] = date('c', $node->created);
  $row['posted_time'] = (int)$node->created;

  return $row;
}

/**
 * Implements hook_node_access().
 */
function uib_message_node_access($node, $op, $account) {
  if (is_object($node) && $node->type == 'uib_message') {
    if ($op == 'update' || $op == 'delete') {
      if (in_array('level 2', $account->roles) || in_array('level 3', $account->roles)) {
        $area = node_load($node->field_uib_message_area['und'][0]['target_id']);
        if (!uib_area__is_content_manager($area, $account))
          return NODE_ACCESS_DENY;
      }
    }
  }
  return NODE_ACCESS_IGNORE;
}

/**
 * Implements hook_node_validate().
 */
function uib_message_node_validate($node, $form, &$form_state) {
  if ($form["#form_id"] == "uib_message_node_form") {
    global $user;
    if (!in_array('level 1', $user->roles) && $user->uid != 1) {
      $area_id = $form_state['values']['field_uib_message_area']['und'][0]['target_id'];
      if ($area_id != "") {
        $area_node = node_load($area_id);
        if (!uib_area__is_content_manager($area_node, $user)) {
          $message = t('You must be content manager of ');
          $message .= t('the area'); // split because then we already have the translations from uib_article
          form_set_error('field_uib_message_area', $message . ': ' . $area_node->title);
        }
      }
    }
  }
}

/**
 * Implements hook_page_alter()
 *
 * Adding title to the message pages
 */
function uib_message_page_alter(&$page) {
  $qp = drupal_get_query_parameters();
  $path = current_path();
  $tags = false;
  if (!preg_match('/messages/',$path)) return;
  $title = "";
  if (current_path() == 'messages') {
    $title = t('All recent messages');
  } else {
    $area = explode('/', $path);
    if ($qp) $tags = explode(',', $qp['tag']);
    $node = node_load($area[1]);
    if (!$tags) {
      if ($node->nid == 1 || $node->nid == 2) {
        $title = t('Recent messages for employees');
      } else {
        $title = t('Recent messages from the @area', array('@area' => $node->title));
      }
    } else if (count($tags) == 1) {
      $title = t('Recent @tag messages from the @area',
        array('@tag' => check_plain(strtolower($tags[0])), '@area' => $node->title));
    } else {
      $tagsarr = array();
      $tagsarr["@" . check_plain($tags[0])] = check_plain(strtolower($tags[0]));
      $str = "Recent @" . check_plain($tags[0]);
      for ($i = 2; $i <= count($tags); $i++) {
        $area = check_plain(strtolower($tags[$i-1]));
        if ($i < count($tags)) $str .= ", ";
        else if ($i == count($tags)) $str .= " and ";
        $str .= "@" . $area;
        $tagsarr["@" . $area] = $area;
      }
      $tagsarr['@area'] = check_plain($node->title);
      $str .= " messages from the @area";
      $title = t($str, $tagsarr);
    }
  }
  $page['content_top']['title'] = array(
    "#weight" => -10,
    "#markup" => "<h1 class='uib_message_title'>". $title . "</h1>",
  );
}


/**
 * Implements hook_node_view().
 *
 * Messages are too dynamic to set up using the regular display settings, so we
 * fill up the content here.
 */
function uib_message_node_view($node, $view_mode, $langcode) {
  if ($node->type != 'uib_message')
    return;
  $tag = taxonomy_term_load($node->field_uib_message_tag['und'][0]['target_id']);
  $tagI = explode('/',$tag->name);
  $tagP = ($langcode == 'nb' ? $tagI[0] : $tagI[1]);
  $node->content['tag'] = array(
    '#markup' => '<div class="message-tag" title="' . $tag->name . '">' . $tagP . '</div>',
  );
  $lang_pref[] = $langcode;
  $lang_pref[] = $langcode == 'nb' ? 'en' : 'nb';

  $message = '';
  $link = null;
  foreach ($lang_pref as $lang) {
    $field = 'field_uib_message_text_' . $lang;
    $field = $node->$field;
    if (!empty($field)) {
      $message = $field['und'][0]['value'];
    }
    if ($message) {
      $field = 'field_uib_message_link_' . $lang;
      $field = $node->$field;
      if (!empty($field)) {
        $link = $field['und'][0]['url'];
      }
      break;
    }
  }
  $message = '<span class="text">' . check_plain($message) . '</span>';
  $message_area_print = false;
  $current_area = uib_area__get_current();
  if (!$current_area || $node->field_uib_message_area['und'][0]['target_id'] != $current_area->tnid) {
    $message_area = node_load($node->field_uib_message_area['und'][0]['target_id']);
    $message_area = uib_area__get_current_by_language($message_area);
    $message_area_print = '<span class="message-area-from">' . l(check_plain($message_area->title), "node/$message_area->nid") . '</span> ';
  }
  if ($link) {
    $message .= ' <span class="message-link">' . l(t('Read more') . '…', $link) . '</span>';
  }
  $node->content['message_text'] = array(
    '#markup' => '<div class="message-text">' . $message . '</div>',
  );

  if (node_access('update', $node)) {
    $node->content['links']['node']['#links']['edit'] = array(
      'title' => t('edit'),
      'href' => 'node/' . $node->nid . '/edit',
    );
  }
  if (node_access('delete', $node)) {
    $node->content['links']['node']['#links']['delete'] = array(
      'title' => t('delete'),
      'href' => 'node/' . $node->nid . '/delete',
    );
  }
  if($message_area_print){
    $node->content['message_area'] = array(
      '#markup' => $message_area_print,
    );
  }
  $node->content['message_age'] = array(
    '#markup' => '<div class="message-age">' . format_interval(time() - $node->created, 1) . ' ' . t('ago') . '</div>',
  );
}

/**
 * Implements hook_node_presave().
 *
 * Changing nid of target to tnid
 */
function uib_message_node_presave($node) {
  if ($node->type != 'uib_message')
    return;

  $node->title =
    substr($node->field_uib_message_text_nb['und'][0]['value'],0,49) . " / " .
    substr($node->field_uib_message_text_en['und'][0]['value'],0,49);

  $area_nid = $node->field_uib_message_area['und'][0]['target_id'];
  $area_tnid = $area_nid; // default in case no translation is found

  global $language;
  $result = db_query("SELECT nid, tnid FROM {node} WHERE language = :lang AND tnid IN (SELECT tnid FROM {node} WHERE nid = :area)",
    array(':area' => $area_nid, ':lang' => $language->language))->fetchAll();
  if (!empty($result)) {
    $area_nid = $result[0]->nid;
    $area_tnid = $result[0]->tnid;
  }
  $node->field_uib_message_area['und'][0]['target_id'] = $area_tnid;
  $_GET['destination'] = drupal_get_path_alias("node/$area_nid/messages", $language->language); // cause redirection after the save
}

/**
 * Implements hook_form_alter().
 */
function uib_message_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'uib_message_node_form') {
    $form['title']['#default_value'] = 'New UIB message';
    $form['title']['#access'] = FALSE;
  }
}

/**
 * Implements hook_block_info().
 */
function uib_message_block_info() {
  $block = array();
  $block['uib_message_block'] = array(
    'info' => t('Message block title'),
    'status' => TRUE,
  );
  return $block;
}

/**
 * Implements hook_block_view().
 */
function uib_message_block_view($delta = '') {
  $block = array();
  switch($delta) {
  case 'uib_message_block' :
    $block['subject'] = 'Messages';
    $block['content'] = uib_message__block_content();
    break;
  }
  return $block;
}

/**
 * Implements custom function to render message block
 */
function uib_message__block_content() {
  drupal_add_js(drupal_get_path('module','uib_message') . '/msg-block.js');
  $node = menu_get_object();
  $output = "<div id='messages-block-content'>".t('Loading...')
    ."</div><noscript>"
    .l(t('Link to alternative'),'node/'
    .$node->nid.'/messages')."</noscript>";
  return $output;
}

/**
 * Implements hook_views_query_alter().
 *
 * Will search the taxonomy term data for possible URL matches
 */
function uib_message_views_query_alter(&$view, &$query) {
  if ($view->name == 'uib_message') {
    $taxonomy_ids = array();
    $q = drupal_get_query_parameters();
    $param = false;
    if (isset($q['tag'])) {
      $param = explode(',', $q['tag']);
    }
    $field = "field_data_field_uib_message_tag.field_uib_message_tag_target_id";
    if (count($param) >= 1 && $param) {
      $uib_message_tag_tree = taxonomy_get_tree(38); // the 'uib_message_tag' vocabulary
      foreach ($uib_message_tag_tree as $obj) {
        $tax_arr = explode('/', $obj->name);
        if (in_array($tax_arr[0], $param) || in_array($tax_arr[1], $param)) {
          $taxonomy_ids[] = $obj->tid;
        }
      }
      if (count($taxonomy_ids) == 1) {
        $query->add_where(0, $field, $taxonomy_ids[0], '=');
      }
      else {
        $db_or = db_or();
        foreach ($taxonomy_ids as $tid) {
          $db_or->condition($field, $tid, '=');
        }
        $query->add_where(3, $db_or);
      }
    }
  }
}
