<?php
/**
 * Implements hook_field_attach_view_alter().
 */
function uib_field_field_attach_view_alter(&$output, $context) {
  foreach ($output as $key => $item) {
    // Check before displaying if field is empty and hide it if it is.
    // Used to stop an empty label to appear when field is empty
    if (substr($key, 0 , 6) == 'field_') {
      if (isset($item['#items']['0']['value']) AND empty($item['#items']['0']['value'])) {
        hide($output[$key]); // hide empty text fields
      }
      elseif (isset($item['#items']['0']['entity']) AND empty($item['#items']['0']['entity'])) {
        hide($output[$key]); // hide fields with lacking entities (unclear if such exist)
      }
    }
  }
}



/**
 * Implements hook_field_formatter_info().
 */
function uib_field_field_formatter_info() {
  return array(
    'socialmedia_formatter' => array( //Machine name of the formatter
      'label' => t('Social Media Links'),
      'field types' => array('text'), //This will only be available to text fields
      'description' => t('Format a text of a specific format into social media links'),
    ),
  );
}


/**
 * Implements hook_field_formatter_view().
 */
function uib_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $recognized_social_media = array( // media name => array ( site url, default)
    'facebook' => array('https://facebook.com/', 'https://facebook.com/unibergen'),
    'twitter' => array('https://twitter.com/', 'https://twitter.com/uib'),
    'youtube' => array('https://www.youtube.com/user/', 'https://www.youtube.com/user/UniBergen'),
    'flickr' => array('https://www.flickr.com/', 'https://www.flickr.com/photos/unibergen/'),
    'vimeo' => array('https://vimeo.com/', 'https://vimeo.com/uib'),
    'instagram' => array('https://www.instagram.com/', 'https://www.instagram.com/unibergen/'),
    'github' => array('https://github.com/', 'https://github.com/uib'),
    'linkedin' => array('https://linkedin.com/in/', 'https://linkedin.com/edu/school/15492'),
    'researchgate' => array('https://www.researchgate.net/profile/', 'https://www.researchgate.net/institution/University_of_Bergen'),
    'snapchat' => array('https://www.snapchat.com/add/', 'https://www.snapchat.com/add/'),
    'orcid' => array('https://orcid.org/', 'https://orcid.org'),
    'googlescholar' => array('https://scholar.google.com/citations?user=', 'https://scholar.google.com/citations?view_op=view_org&org=8898899287978071111'),
    'academia' => array('https://uib.academia.edu/', 'https://uib.academia.edu'),
    'researcherid' => array('http://www.researcherid.com/rid/', 'http://www.researcherid.com'),
    'scopus' => array('https://www.scopus.com/authid/detail.uri?authorId=', 'https://www.scopus.com'),
    'dblp' => array('http://dblp.uni-trier.de/rec/pid/', 'http://dblp.uni-trier.de'),
    'gitlab' => array('https://gitlab.com/', 'https://gitlab.com/uib'),
    'gitlabuib' => array('https://git.app.uib.no/', 'https://git.app.uib.no/'),
    'philpeople' => array('https://philpeople.org/profiles/', 'https://philpeople.org/departments/bergen/'),
  );
  foreach ($items as $delta => $item) {
    $sm = explode(':', $item['safe_value']);
    $sm_name = array_shift($sm);
    $sm_name = trim($sm_name);
    $sm_data = implode(':', $sm);
    if (!empty($recognized_social_media[$sm_name])) {
      if (!empty($sm_data)) {
        $sm_url = $recognized_social_media[$sm_name][0] . $sm_data;
      }
      else {
        $sm_url = $recognized_social_media[$sm_name][1]; // use default
      }
      $titles = array(
        'academia' => 'Academia',
        'dblp' => 'dblp',
        'facebook' => 'Facebook',
        'flickr' => 'Flickr',
        'github' => 'GitHub',
        'gitlab' => 'GitLab',
        'gitlabuib' => 'GitLab UiB',
        'googlescholar' => 'Google Scholar',
        'instagram' => 'Instagram',
        'linkedin' => 'LinkedIn',
        'orcid' => 'ORCID',
        'philpeople' => 'PhilPeople',
        'researcherid' => 'ResearcherID',
        'researchgate' => 'ResearchGate',
        'scopus' => 'Scopus',
        'snapchat' => 'Snapchat',
        'twitter' => 'Twitter',
        'vimeo' => 'Vimeo',
        'youtube' => 'YouTube',
      );
      $follow = ($entity_type == 'user' ? t('Follow me on') : t('Follow us on'));
      $options = array(
        'html'  => TRUE,
        'attributes'  => array(
          'class' => array('icons-social-' . $sm_name),
          'title' => $follow . ' ' . $titles[$sm_name],
        ),
      );
      $options['attributes']['onClick'] = "ga('send', {'hitType':'$sm_name', 'eventCategory':'SocialMediaButtons', 'eventAction':'Follow', 'eventLabel':'" .current_path() . "'})";
      $element[]['#markup'] = l($sm_name, $sm_url, $options);
    }
  }
  return $element;
}
