<?php
  function uib_admin_preprocess_html (&$variables) {
    if (drupal_static('uib_admin_unpublished')) {
      $variables['classes_array'][] = 'unpublished';
    }
    $suggestions = array(
      'html__node__add',
      'html__node__edit',
      'html__node__staff_status',
      'html__node__ties',
      'html__node__translate',
      'html__node__revisions',
      'html__user__edit',
      'html__user__translate',
      'html__webdesk',
      'html__media__browser',
    );
    global $theme;
    if ($theme == 'adminimal') {
      drupal_add_css(drupal_get_path('module','uib_admin') . '/css/uib_admin.css', array('group' => CSS_THEME));
    }
  }
  function uib_admin_admin_paths () {
    $paths = array(
      'node/*/staff_status' => true,
      'node/*/ties' => true,
      'node/*/menu' => true,
      'node/*/tmenu' => true,
      'node/*/share' => true,
      'user/*/edit' => true,
      'user/login' => true,
      'webdesk' => true,
      'webdesk/*' => true,
    );
    global $user;
    if ($user->uid == 0) {
      $paths['user'] = true;
    }
    return $paths;
  }

  function uib_admin_node_presave ($node) {
    $n = entity_metadata_wrapper('node', $node);
    $text = $n->field_uib_text->value();
    if (strpos($text['value'], '(* exams:') !== FALSE) {
      $list = variable_get(
        'uib_exams_list_nodes',
        // These nodes display the exams list today. The list will be
        // initialized when any of these are saved the first time:
        array(
          108689,
          108687,
          108651,
          108650,
          108414,
          108382,
          108378,
          108370,
          108686,
          108374,
          108384,
          108381,
          108376,
          108377,
        )
      );
      if (!in_array($node->nid, $list)) {
        $list[] = $node->nid;
      }
      variable_set('uib_exams_list_nodes', $list);
    }
  }
