<?php
/**
 * @file
 * Code for the UiB market feature.
 */

include_once 'uib_market.features.inc';
/**
 * @file
 * Code for the UiB internal market module and feature.
 */

/**
 * Implements hook_node_view().
 */
function uib_market_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'uib_market') {
    // Force employee pages area when displaying a uib_market node
    $nid = ($langcode == 'nb') ?
      intval(variable_get('uib_ansatte_nb_nid')) :
      intval(variable_get('uib_ansatte_en_nid'));
    uib_area__get_current($nid);
  }
}

/**
 * Implements hook_preprocess_HOOK()
 */
function uib_market_preprocess_views_view(&$variables) {
  global $language;
  if ($variables['name'] == 'internal_market') {
    if ($variables['display_id'] == 'page') {
      // Force employee pages area for the view page display
      $nid = ($language->language == 'nb') ?
        intval(variable_get('uib_ansatte_nb_nid')) :
        intval(variable_get('uib_ansatte_en_nid'));
      uib_area__get_current($nid);
    }
  }
}

/**
 * Implements hook_views_pre_render()
 */
function uib_market_views_pre_render($view) {
  if ($view->name != 'internal_market')
    return;
  $field_info = field_info_field('field_uib_market_category');
  foreach($field_info['settings']['allowed_values'] as $cat => $cat_value) {
    $view->exposed_widgets = str_replace(
      $cat_value,
      i18n_string_translate("field:field_uib_market_category:#allowed_values:$cat", $cat_value),
      $view->exposed_widgets
    );
  }
}

/**
 * Implements hook_node_update()
 */
function uib_market_node_update($node) {
  if ($node->type == 'uib_market') {
    __uib_market__set_alias($node, 'nb');
    __uib_market__set_alias($node, 'en');
  }
}

/**
 * Implements hook_node_insert()
 */
function uib_market_node_insert($node) {
  if ($node->type == 'uib_market') {
    __uib_market__set_alias($node, 'nb');
    __uib_market__set_alias($node, 'en');
  }
}

function __uib_market__set_alias($node, $language=null) {
  $old_path = path_load('node/' . $node->nid);
  $path_text = ($language == 'nb') ? 'foransatte/marked/' : 'foremployees/market/' ;
  $path = array(
    'source' => 'node/' . $node->nid,
    'alias' => $path_text . $node->nid . '/' . str_replace(' ', '-', strtolower($node->title)),
    'language' => $language,
  );
  if ($old_path['alias'] != $path['alias']) {
    path_save($path);
  }
}
