<?php
/**
 * @file
 * Code for the UiB Development support feature.
 */

include_once 'uib_devel.features.inc';

/*
 * Implements hook_entity_view_alter().
 */

function uib_devel_entity_view_alter(&$build, $type) {
  if (isset($build['field_uib_sebra_id'])) {
    $sebra_id =  $build['field_uib_sebra_id'][0]['#markup'];
    $build['field_uib_sebra_id'][0]['#markup'] = '<a href="http://sebra.uib.no/sws/omraader?omraadekode=' . $sebra_id . '">' . $sebra_id . '</a>';
  }
}
