<?php
/**
 * @file
 * Code for the UiB Views overrides feature.
 */

include_once 'uib_views.features.inc';

/**
 * Implements hook_views_query_alter().
 */
function uib_views_views_query_alter(&$view, &$query) {
  if ($view->name == 'ansatte') {

    if (!empty($query->where[0]['conditions'][0])) {
      $alias = '';
      foreach ($view->args as $value) {
        $alias .= $value . '/';
      }

      $alias = rtrim($alias, "/");
      $node = drupal_get_normal_path($alias, $language = NULL);

      if ($alias != $node) {
        $nid = substr(strrchr($node, "/"), 1);
        $query->where[0]['conditions'][0]['value'][':node_nid'] = $nid;
      }
    }
  }
}

/**
 * Implements hook_views_bulk_operations_form_alter().
 */
function uib_views_views_bulk_operations_form_alter(&$form, &$form_state, $vbo) {
  global $user;

  if (in_array('level 3', $user->roles)) {
    if (in_array('level 1', $user->roles) || in_array('level 2', $user->roles)) {
    }
    else {
      $form['select_all']['#access'] = FALSE;
      $form['select']['#access'] = FALSE;
      unset($form['views_bulk_operations']);
      unset($form['#parents']);
    }
  }
}

/**
 * Implements hook_block_view_alter().
 */
function uib_views_block_view_alter(&$data, $block) {
  if (!empty($data['subject'])) {
    if ($data['subject'] == 'Recent news') {
      if (uib_area__is_employee_page()) {
        $data['subject'] = 'Messages';
      }
    }
  }
}

/**
 * Implements hook_node_view().
 */
function uib_views_node_view($node, $view_mode, $langcode) {
  if (!path_is_admin(current_path())) {
    if ($node->type == 'uib_views_page' && $view_mode == 'full') {
      // Title
      $node->content['field_uib_node_title'][0]['#markup'] =
        '<h1 class="title">' . $node->content['field_uib_node_title'][0]['#markup'] . '</h1>';
      // Display a view in a block
      if (!empty($node->field_uib_view_block_name['und'])) {
        $block = block_load('views', $node->field_uib_view_block_name['und'][0]['safe_value']);
        $block_content = _block_render_blocks(array($block));
        $render = _block_get_renderable_array($block_content);
        $render['#weight'] = 99;
        $node->content['uib_views_block'] = $render;
      }
    }
  }
}

/**
 * Implements hook_node_access().
 *
 * Control access to edit view page content.
 */
function uib_views_node_access($node, $op, $user) {
  if ($op == 'view') {
    return NODE_ACCESS_IGNORE;
  }
  // $op is one of 'create', 'update', 'delete'
  if (is_object($node) && $node->type == 'uib_views_page') {
    if (isset($node->field_uib_area['und'][0]['target_id'])) {
      // Node is attached to an area
      $area = node_load($node->field_uib_area['und'][0]['target_id']);
      if (!uib_area__is_content_manager($area, $user)) {
        return NODE_ACCESS_DENY;
      }
    }
    else {
      return NODE_ACCESS_DENY;
    }
  }
  return NODE_ACCESS_IGNORE;
}
